version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "wife_storage"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - wife.storage-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  storage:
    depends_on:
      - postgres
    build: ./
    environment:
      WIFEDB: "wife_storage"
      WIFEHOST: "postgres"
      WIFEPORT: "5432"
      WIFEPROVIDER: "postgres"
      WIFEEUSER: "admin"
      WIFEPASSWORD: "password"
    ports:
      - 8090:8090
volumes:
  wife.storage-data: